services:
  frontend:
    build: ./frontend
    expose:
      - "5173"             # for internal access (Cloudflared)
    ports:
      - "5173:5173"        # if you want to reach it directly on the Pi
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    expose: ["5000"]
    environment:
      SECRET_KEY: ${SECRET_KEY}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      DOMAIN_ORIGINS: ${DOMAIN_ORIGINS}
      USERS: ${USERS}
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

volumes:
  backend_data: