services:
  frontend:
    build: ./frontend
    expose:
      - "5173"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    expose: ["5000"]
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

volumes:
  backend_data:
